nor = 0.5
moun = 8.0
accid = 15.0

edges = [
        ('A0', 'B0', nor),
        ('A0', 'B1', nor),
        ('A0', 'A1', nor),

        ('A1', 'A0', nor),
        ('A1', 'B0', nor),
        ('A1', 'B1', nor),
        ('A1', 'B2', nor),
        ('A1', 'A2', nor),

        ('A2', 'B1', nor),
        ('A2', 'B2', nor),
        ('A2', 'B3', nor),
        ('A2', 'A3', nor),
        ('A2', 'A1', nor),

        ('A3', 'A2', nor),
        ('A3', 'B2', nor),
        ('A3', 'B3', nor),
        ('A3', 'B4', nor),
        ('A3', 'A4', nor),

        ('A4', 'A3', nor),
        ('A4', 'B3', nor),
        ('A4', 'B4', nor),
        ('A4', 'B5', nor),
        ('A4', 'A5', nor),

        ('A5', 'A4', nor),
        ('A5', 'B4', nor),
        ('A5', 'B5', nor),
        ('A5', 'B6', nor),
        ('A5', 'A6', nor),

        ('A6', 'A5', nor),
        ('A6', 'B5', nor),
        ('A6', 'B6', nor),
        ('A6', 'B7', nor),
        ('A6', 'A7', nor),

        ('A7', 'A6', nor),
        ('A7', 'B6', nor),
        ('A7', 'B7', nor),
        ('A7', 'B8', nor),
        ('A7', 'A8', nor),

        ('A8', 'A7', nor),
        ('A8', 'B7', nor),
        ('A8', 'B8', nor),
        ('A8', 'B9', nor),
        ('A8', 'A9', nor),

        ('A9', 'A8', nor),
        ('A9', 'B8', nor),
        ('A9', 'B9', nor),

        ('B0', 'A0', nor),
        ('B0', 'A1', nor),
        ('B0', 'B1', nor),
        ('B0', 'C1', nor),
        ('B0', 'C0', nor),

        ('B1', 'A0', nor),
        ('B1', 'B0', nor),
        ('B1', 'C0', nor),
        ('B1', 'A1', nor),
        ('B1', 'C1', nor),
        ('B1', 'A2', nor),
        ('B1', 'B2', nor),
        ('B1', 'C2', nor),

        ('B2', 'A1', nor),
        ('B2', 'B1', nor),
        ('B2', 'C1', nor),
        ('B2', 'A2', nor),
        ('B2', 'C2', nor),
        ('B2', 'A3', nor),
        ('B2', 'B3', nor),
        ('B2', 'C3', nor),

        ('B3', 'A2', nor),
        ('B3', 'B2', nor),
        ('B3', 'C2', nor),
        ('B3', 'A3', nor),
        ('B3', 'C3', nor),
        ('B3', 'A4', nor),
        ('B3', 'B4', nor),
        ('B3', 'C4', nor),

        ('B4', 'A3', nor),
        ('B4', 'B3', nor),
        ('B4', 'C3', nor),
        ('B4', 'A4', nor),
        ('B4', 'C4', nor),
        ('B4', 'A5', nor),
        ('B4', 'B5', nor),
        ('B4', 'C5', nor),

        ('B5', 'A4', nor),
        ('B5', 'B4', nor),
        ('B5', 'C4', nor),
        ('B5', 'A5', nor),
        ('B5', 'C5', nor),
        ('B5', 'A6', nor),
        ('B5', 'B6', nor),
        ('B5', 'C6', nor),

        ('B6', 'A5', nor),
        ('B6', 'B5', nor),
        ('B6', 'C5', nor),
        ('B6', 'A6', nor),
        ('B6', 'C6', nor),
        ('B6', 'A7', nor),
        ('B6', 'B7', nor),
        ('B6', 'C7', nor),

        ('B7', 'A6', nor),
        ('B7', 'B6', nor),
        ('B7', 'C6', nor),
        ('B7', 'A7', nor),
        ('B7', 'C7', nor),
        ('B7', 'A8', nor),
        ('B7', 'B8', nor),
        ('B7', 'C8', nor),

        ('B8', 'A7', nor),
        ('B8', 'B7', nor),
        ('B8', 'C7', nor),
        ('B8', 'A8', nor),
        ('B8', 'C8', nor),
        ('B8', 'A9', nor),
        ('B8', 'B9', nor),
        ('B8', 'C9', nor),

        ('B9', 'A9', nor),
        ('B9', 'A8', nor),
        ('B9', 'B8', nor),
        ('B9', 'C8', nor),
        ('B9', 'C9', nor),

        ('C0', 'B0', nor),
        ('C0', 'B1', nor),
        ('C0', 'C1', nor),
        ('C0', 'D1', nor),
        ('C0', 'D0', nor),

        ('C1', 'B0', nor),
        ('C1', 'C0', nor),
        ('C1', 'D0', nor),
        ('C1', 'B1', nor),
        ('C1', 'D1', nor),
        ('C1', 'B2', nor),
        ('C1', 'C2', nor),
        ('C1', 'D2', nor),

        ('C2', 'B1', nor),
        ('C2', 'C1', nor),
        ('C2', 'D1', nor),
        ('C2', 'B2', nor),
        ('C2', 'D2', nor),
        ('C2', 'B3', nor),
        ('C2', 'C3', nor),
        ('C2', 'D3', nor),

        ('C3', 'B2', nor),
        ('C3', 'C2', nor),
        ('C3', 'D2', nor),
        ('C3', 'B3', nor),
        ('C3', 'D3', nor),
        ('C3', 'B4', nor),
        ('C3', 'C4', nor),
        ('C3', 'D4', nor),

        ('C4', 'B3', nor),
        ('C4', 'C3', nor),
        ('C4', 'D3', nor),
        ('C4', 'B4', nor),
        ('C4', 'D4', nor),
        ('C4', 'B5', nor),
        ('C4', 'C5', nor),
        ('C4', 'D5', nor),

        ('C5', 'B4', nor),
        ('C5', 'C4', nor),
        ('C5', 'D4', nor),
        ('C5', 'B5', nor),
        ('C5', 'D5', nor),
        ('C5', 'B6', nor),
        ('C5', 'C6', nor),
        ('C5', 'D6', nor),

        ('C6', 'B5', nor),
        ('C6', 'C5', nor),
        ('C6', 'D5', nor),
        ('C6', 'B6', nor),
        ('C6', 'D6', nor),
        ('C6', 'B7', nor),
        ('C6', 'C7', nor),
        ('C6', 'D7', nor),

        ('C7', 'B6', nor),
        ('C7', 'C6', nor),
        ('C7', 'D6', nor),
        ('C7', 'B7', nor),
        ('C7', 'D7', nor),
        ('C7', 'B8', nor),
        ('C7', 'C8', nor),
        ('C7', 'D8', nor),

        ('C8', 'B7', nor),
        ('C8', 'C7', nor),
        ('C8', 'D7', nor),
        ('C8', 'B8', nor),
        ('C8', 'D8', nor),
        ('C8', 'B9', nor),
        ('C8', 'C9', nor),
        ('C8', 'D9', nor),

        ('C9', 'B9', nor),
        ('C9', 'B8', nor),
        ('C9', 'C8', nor),
        ('C9', 'D8', nor),
        ('C9', 'D9', nor),

        ('D0', 'C0', nor),
        ('D0', 'C1', nor),
        ('D0', 'D1', nor),
        ('D0', 'E1', nor),
        ('D0', 'E0', nor),

        ('D1', 'C0', nor),
        ('D1', 'D0', nor),
        ('D1', 'E0', nor),
        ('D1', 'C1', nor),
        ('D1', 'E1', nor),
        ('D1', 'C2', nor),
        ('D1', 'D2', nor),
        ('D1', 'E2', nor),

        ('D2', 'C1', nor),
        ('D2', 'D1', nor),
        ('D2', 'E1', nor),
        ('D2', 'C2', nor),
        ('D2', 'E2', nor),
        ('D2', 'C3', nor),
        ('D2', 'D3', nor),
        ('D2', 'E3', nor),

        ('D3', 'C2', nor),
        ('D3', 'D2', nor),
        ('D3', 'E2', nor),
        ('D3', 'C3', nor),
        ('D3', 'E3', nor),
        ('D3', 'C4', nor),
        ('D3', 'D4', nor),
        ('D3', 'E4', nor),

        ('D4', 'C3', nor),
        ('D4', 'D3', nor),
        ('D4', 'E3', nor),
        ('D4', 'C4', nor),
        ('D4', 'E4', nor),
        ('D4', 'C5', nor),
        ('D4', 'D5', nor),
        ('D4', 'E5', nor),

        ('D5', 'C4', nor),
        ('D5', 'D4', nor),
        ('D5', 'E4', nor),
        ('D5', 'C5', nor),
        ('D5', 'E5', nor),
        ('D5', 'C6', nor),
        ('D5', 'D6', nor),
        ('D5', 'E6', nor),

        ('D6', 'C5', nor),
        ('D6', 'D5', nor),
        ('D6', 'E5', nor),
        ('D6', 'C6', nor),
        ('D6', 'E6', nor),
        ('D6', 'C7', nor),
        ('D6', 'D7', nor),
        ('D6', 'E7', nor),

        ('D7', 'C6', nor),
        ('D7', 'D6', nor),
        ('D7', 'E6', nor),
        ('D7', 'C7', nor),
        ('D7', 'E7', nor),
        ('D7', 'C8', nor),
        ('D7', 'D8', nor),
        ('D7', 'E8', nor),

        ('D8', 'C7', nor),
        ('D8', 'D7', nor),
        ('D8', 'E7', nor),
        ('D8', 'C8', nor),
        ('D8', 'E8', nor),
        ('D8', 'C9', nor),
        ('D8', 'D9', nor),
        ('D8', 'E9', nor),

        ('D9', 'C9', nor),
        ('D9', 'C8', nor),
        ('D9', 'D8', nor),
        ('D9', 'E8', nor),
        ('D9', 'E9', nor),

        ('E0', 'D0', nor),
        ('E0', 'D1', nor),
        ('E0', 'E1', nor),
        ('E0', 'F1', nor),
        ('E0', 'F0', nor),

        ('E1', 'D0', nor),
        ('E1', 'E0', nor),
        ('E1', 'F0', nor),
        ('E1', 'D1', nor),
        ('E1', 'F1', nor),
        ('E1', 'D2', nor),
        ('E1', 'E2', nor),
        ('E1', 'F2', nor),

        ('E2', 'D1', nor),
        ('E2', 'E1', nor),
        ('E2', 'F1', nor),
        ('E2', 'D2', nor),
        ('E2', 'F2', nor),
        ('E2', 'D3', nor),
        ('E2', 'E3', nor),
        ('E2', 'F3', nor),

        ('E3', 'D2', nor),
        ('E3', 'E2', nor),
        ('E3', 'F2', nor),
        ('E3', 'D3', nor),
        ('E3', 'F3', nor),
        ('E3', 'D4', nor),
        ('E3', 'E4', nor),
        ('E3', 'F4', nor),

        ('E4', 'D3', nor),
        ('E4', 'E3', nor),
        ('E4', 'F3', nor),
        ('E4', 'D4', nor),
        ('E4', 'F4', nor),
        ('E4', 'D5', nor),
        ('E4', 'E5', nor),
        ('E4', 'F5', nor),

        ('E5', 'D4', nor),
        ('E5', 'E4', nor),
        ('E5', 'F4', nor),
        ('E5', 'D5', nor),
        ('E5', 'F5', nor),
        ('E5', 'D6', nor),
        ('E5', 'E6', nor),
        ('E5', 'F6', nor),

        ('E6', 'D5', nor),
        ('E6', 'E5', nor),
        ('E6', 'F5', nor),
        ('E6', 'D6', nor),
        ('E6', 'F6', nor),
        ('E6', 'D7', nor),
        ('E6', 'E7', nor),
        ('E6', 'F7', nor),

        ('E7', 'D6', nor),
        ('E7', 'E6', nor),
        ('E7', 'F6', nor),
        ('E7', 'D7', nor),
        ('E7', 'F7', nor),
        ('E7', 'D8', nor),
        ('E7', 'E8', nor),
        ('E7', 'F8', nor),

        ('E8', 'D7', nor),
        ('E8', 'E7', nor),
        ('E8', 'F7', nor),
        ('E8', 'D8', nor),
        ('E8', 'F8', nor),
        ('E8', 'D9', nor),
        ('E8', 'E9', nor),
        ('E8', 'F9', nor),

        ('E9', 'D9', nor),
        ('E9', 'D8', nor),
        ('E9', 'E8', nor),
        ('E9', 'F8', nor),
        ('E9', 'F9', nor),

        ('F0', 'E0', nor),
        ('F0', 'E1', nor),
        ('F0', 'F1', nor),
        ('F0', 'G1', nor),
        ('F0', 'G0', nor),

        ('F1', 'E0', nor),
        ('F1', 'F0', nor),
        ('F1', 'G0', nor),
        ('F1', 'E1', nor),
        ('F1', 'G1', nor),
        ('F1', 'E2', nor),
        ('F1', 'F2', nor),
        ('F1', 'G2', nor),

        ('F2', 'E1', nor),
        ('F2', 'F1', nor),
        ('F2', 'G1', nor),
        ('F2', 'E2', nor),
        ('F2', 'G2', nor),
        ('F2', 'E3', nor),
        ('F2', 'F3', nor),
        ('F2', 'G3', nor),

        ('F3', 'E2', nor),
        ('F3', 'F2', nor),
        ('F3', 'G2', nor),
        ('F3', 'E3', nor),
        ('F3', 'G3', nor),
        ('F3', 'E4', nor),
        ('F3', 'F4', nor),
        ('F3', 'G4', nor),

        ('F4', 'E3', nor),
        ('F4', 'F3', nor),
        ('F4', 'G3', nor),
        ('F4', 'E4', nor),
        ('F4', 'G4', nor),
        ('F4', 'E5', nor),
        ('F4', 'F5', nor),
        ('F4', 'G5', nor),

        ('F5', 'E4', nor),
        ('F5', 'F4', nor),
        ('F5', 'G4', nor),
        ('F5', 'E5', nor),
        ('F5', 'G5', nor),
        ('F5', 'E6', nor),
        ('F5', 'F6', nor),
        ('F5', 'G6', nor),

        ('F6', 'E5', nor),
        ('F6', 'F5', nor),
        ('F6', 'G5', nor),
        ('F6', 'E6', nor),
        ('F6', 'G6', nor),
        ('F6', 'E7', nor),
        ('F6', 'F7', nor),
        ('F6', 'G7', nor),

        ('F7', 'E6', nor),
        ('F7', 'F6', nor),
        ('F7', 'G6', nor),
        ('F7', 'E7', nor),
        ('F7', 'G7', nor),
        ('F7', 'E8', nor),
        ('F7', 'F8', nor),
        ('F7', 'G8', nor),

        ('F8', 'E7', nor),
        ('F8', 'F7', nor),
        ('F8', 'G7', nor),
        ('F8', 'E8', nor),
        ('F8', 'G8', nor),
        ('F8', 'E9', nor),
        ('F8', 'F9', nor),
        ('F8', 'G9', nor),

        ('F9', 'E9', nor),
        ('F9', 'E8', nor),
        ('F9', 'F8', nor),
        ('F9', 'G8', nor),
        ('F9', 'G9', nor),

        ('G0', 'F0', nor),
        ('G0', 'F1', nor),
        ('G0', 'G1', nor),
        ('G0', 'H1', nor),
        ('G0', 'H0', nor),

        ('G1', 'F0', nor),
        ('G1', 'G0', nor),
        ('G1', 'H0', nor),
        ('G1', 'F1', nor),
        ('G1', 'H1', nor),
        ('G1', 'F2', nor),
        ('G1', 'G2', nor),
        ('G1', 'H2', nor),

        ('G2', 'F1', nor),
        ('G2', 'G1', nor),
        ('G2', 'H1', nor),
        ('G2', 'F2', nor),
        ('G2', 'H2', nor),
        ('G2', 'F3', nor),
        ('G2', 'G3', nor),
        ('G2', 'H3', nor),

        ('G3', 'F2', nor),
        ('G3', 'G2', nor),
        ('G3', 'H2', nor),
        ('G3', 'F3', nor),
        ('G3', 'H3', nor),
        ('G3', 'F4', nor),
        ('G3', 'G4', nor),
        ('G3', 'H4', moun),

        ('G4', 'F3', nor),
        ('G4', 'G3', nor),
        ('G4', 'H3', nor),
        ('G4', 'F4', nor),
        ('G4', 'H4', moun),
        ('G4', 'F5', nor),
        ('G4', 'G5', nor),
        ('G4', 'H5', moun),

        ('G5', 'F4', nor),
        ('G5', 'G4', nor),
        ('G5', 'H4', moun),
        ('G5', 'F5', nor),
        ('G5', 'H5', moun),
        ('G5', 'F6', nor),
        ('G5', 'G6', nor),
        ('G5', 'H6', moun),

        ('G6', 'F5', nor),
        ('G6', 'G5', nor),
        ('G6', 'H5', moun),
        ('G6', 'F6', nor),
        ('G6', 'H6', moun),
        ('G6', 'F7', nor),
        ('G6', 'G7', nor),
        ('G6', 'H7', moun),

        ('G7', 'F6', nor),
        ('G7', 'G6', nor),
        ('G7', 'H6', moun),
        ('G7', 'F7', nor),
        ('G7', 'H7', nor),
        ('G7', 'F8', nor),
        ('G7', 'G8', nor),
        ('G7', 'H8', nor),

        ('G8', 'F7', nor),
        ('G8', 'G7', nor),
        ('G8', 'H7', nor),
        ('G8', 'F8', nor),
        ('G8', 'H8', nor),
        ('G8', 'F9', nor),
        ('G8', 'G9', nor),
        ('G8', 'H9', nor),

        ('G9', 'F9', nor),
        ('G9', 'F8', nor),
        ('G9', 'G8', nor),
        ('G9', 'H8', nor),
        ('G9', 'H9', nor),

        ('H0', 'G0', nor),
        ('H0', 'G1', nor),
        ('H0', 'H1', nor),
        ('H0', 'I1', nor),
        ('H0', 'I0', nor),

        ('H1', 'G0', nor),
        ('H1', 'H0', nor),
        ('H1', 'I0', nor),
        ('H1', 'G1', nor),
        ('H1', 'I1', nor),
        ('H1', 'G2', nor),
        ('H1', 'H2', nor),
        ('H1', 'I2', nor),

        ('H2', 'G1', nor),
        ('H2', 'H1', nor),
        ('H2', 'I1', nor),
        ('H2', 'G2', nor),
        ('H2', 'I2', nor),
        ('H2', 'G3', nor),
        ('H2', 'H3', nor),
        ('H2', 'I3', nor),

        ('H3', 'G2', nor),
        ('H3', 'H2', nor),
        ('H3', 'I2', nor),
        ('H3', 'G3', nor),
        ('H3', 'I3', nor),
        ('H3', 'G4', nor),
        ('H3', 'H4', moun),
        ('H3', 'I4', moun),

        ('H4', 'G3', nor),
        ('H4', 'H3', nor),
        ('H4', 'I3', nor),
        ('H4', 'G4', nor),
        ('H4', 'I4', nor),
        ('H4', 'G5', nor),
        ('H4', 'H5', nor),
        ('H4', 'I5', nor),

        ('H5', 'G4', nor),
        ('H5', 'H4', nor),
        ('H5', 'I4', nor),
        ('H5', 'G5', nor),
        ('H5', 'I5', nor),
        ('H5', 'G6', nor),
        ('H5', 'H6', nor),
        ('H5', 'I6', nor),

        ('H6', 'G5', nor),
        ('H6', 'H5', nor),
        ('H6', 'I5', nor),
        ('H6', 'G6', nor),
        ('H6', 'I6', nor),
        ('H6', 'G7', nor),
        ('H6', 'H7', nor),
        ('H6', 'I7', nor),

        ('H7', 'G6', moun),
        ('H7', 'H6', moun),
        ('H7', 'I6', moun),
        ('H7', 'G7', nor),
        ('H7', 'I7', nor),
        ('H7', 'G8', nor),
        ('H7', 'H8', nor),
        ('H7', 'I8', nor),

        ('H8', 'G7', nor),
        ('H8', 'H7', nor),
        ('H8', 'I7', nor),
        ('H8', 'G8', nor),
        ('H8', 'I8', nor),
        ('H8', 'G9', nor),
        ('H8', 'H9', nor),
        ('H8', 'I9', nor),

        ('H9', 'G9', nor),
        ('H9', 'G8', nor),
        ('H9', 'H8', nor),
        ('H9', 'I8', nor),
        ('H9', 'I9', nor),

        ('I0', 'H0', nor),
        ('I0', 'H1', nor),
        ('I0', 'I1', nor),
        ('I0', 'J1', nor),
        ('I0', 'J0', nor),

        ('I1', 'H0', nor),
        ('I1', 'I0', nor),
        ('I1', 'J0', nor),
        ('I1', 'H1', nor),
        ('I1', 'J1', nor),
        ('I1', 'H2', nor),
        ('I1', 'I2', nor),
        ('I1', 'J2', nor),

        ('I2', 'H1', nor),
        ('I2', 'I1', nor),
        ('I2', 'J1', nor),
        ('I2', 'H2', nor),
        ('I2', 'J2', nor),
        ('I2', 'H3', nor),
        ('I2', 'I3', nor),
        ('I2', 'J3', nor),

        ('I3', 'H2', nor),
        ('I3', 'I2', nor),
        ('I3', 'J2', nor),
        ('I3', 'H3', nor),
        ('I3', 'J3', nor),
        ('I3', 'H4', moun),
        ('I3', 'I4', moun),
        ('I3', 'J4', moun),

        ('I4', 'H3', nor),
        ('I4', 'I3', nor),
        ('I4', 'J3', nor),
        ('I4', 'H4', nor),
        ('I4', 'J4', nor),
        ('I4', 'H5', nor),
        ('I4', 'I5', nor),
        ('I4', 'J5', nor),

        ('I5', 'H4', nor),
        ('I5', 'I4', nor),
        ('I5', 'J4', nor),
        ('I5', 'H5', nor),
        ('I5', 'J5', nor),
        ('I5', 'H6', nor),
        ('I5', 'I6', nor),
        ('I5', 'J6', nor),

        ('I6', 'H5', nor),
        ('I6', 'I5', nor),
        ('I6', 'J5', nor),
        ('I6', 'H6', nor),
        ('I6', 'J6', nor),
        ('I6', 'H7', nor),
        ('I6', 'I7', nor),
        ('I6', 'J7', nor),

        ('I7', 'H6', moun),
        ('I7', 'I6', moun),
        ('I7', 'J6', moun),
        ('I7', 'H7', nor),
        ('I7', 'J7', nor),
        ('I7', 'H8', nor),
        ('I7', 'I8', nor),
        ('I7', 'J8', nor),

        ('I8', 'H7', nor),
        ('I8', 'I7', nor),
        ('I8', 'J7', nor),
        ('I8', 'H8', nor),
        ('I8', 'J8', nor),
        ('I8', 'H9', nor),
        ('I8', 'I9', nor),
        ('I8', 'J9', nor),

        ('I9', 'H9', nor),
        ('I9', 'H8', nor),
        ('I9', 'I8', nor),
        ('I9', 'J8', nor),
        ('I9', 'J9', nor),

        ('J0', 'I0', nor),
        ('J0', 'I1', nor),
        ('J0', 'J1', nor),
        ('J0', 'K1', nor),
        ('J0', 'K0', nor),

        ('J1', 'I0', nor),
        ('J1', 'J0', nor),
        ('J1', 'K0', nor),
        ('J1', 'I1', nor),
        ('J1', 'K1', nor),
        ('J1', 'I2', nor),
        ('J1', 'J2', nor),
        ('J1', 'K2', nor),

        ('J2', 'I1', nor),
        ('J2', 'J1', nor),
        ('J2', 'K1', nor),
        ('J2', 'I2', nor),
        ('J2', 'K2', nor),
        ('J2', 'I3', nor),
        ('J2', 'J3', nor),
        ('J2', 'K3', nor),

        ('J3', 'I2', nor),
        ('J3', 'J2', nor),
        ('J3', 'K2', nor),
        ('J3', 'I3', nor),
        ('J3', 'K3', nor),
        ('J3', 'I4', moun),
        ('J3', 'J4', moun),
        ('J3', 'K4', moun),

        ('J4', 'I3', nor),
        ('J4', 'J3', nor),
        ('J4', 'K3', nor),
        ('J4', 'I4', nor),
        ('J4', 'K4', nor),
        ('J4', 'I5', nor),
        ('J4', 'J5', nor),
        ('J4', 'K5', nor),

        ('J5', 'I4', nor),
        ('J5', 'J4', nor),
        ('J5', 'K4', nor),
        ('J5', 'I5', nor),
        ('J5', 'K5', nor),
        ('J5', 'I6', nor),
        ('J5', 'J6', nor),
        ('J5', 'K6', nor),

        ('J6', 'I5', nor),
        ('J6', 'J5', nor),
        ('J6', 'K5', nor),
        ('J6', 'I6', nor),
        ('J6', 'K6', nor),
        ('J6', 'I7', nor),
        ('J6', 'J7', nor),
        ('J6', 'K7', nor),

        ('J7', 'I6', moun),
        ('J7', 'J6', moun),
        ('J7', 'K6', moun),
        ('J7', 'I7', nor),
        ('J7', 'K7', nor),
        ('J7', 'I8', nor),
        ('J7', 'J8', nor),
        ('J7', 'K8', nor),

        ('J8', 'I7', nor),
        ('J8', 'J7', nor),
        ('J8', 'K7', nor),
        ('J8', 'I8', nor),
        ('J8', 'K8', nor),
        ('J8', 'I9', nor),
        ('J8', 'J9', nor),
        ('J8', 'K9', nor),

        ('J9', 'I9', nor),
        ('J9', 'I8', nor),
        ('J9', 'J8', nor),
        ('J9', 'K8', nor),
        ('J9', 'K9', nor),

        ('K0', 'J0', nor),
        ('K0', 'J1', nor),
        ('K0', 'K1', nor),
        ('K0', 'L1', nor),
        ('K0', 'L0', nor),

        ('K1', 'J0', nor),
        ('K1', 'K0', nor),
        ('K1', 'L0', nor),
        ('K1', 'J1', nor),
        ('K1', 'L1', nor),
        ('K1', 'J2', nor),
        ('K1', 'K2', nor),
        ('K1', 'L2', nor),

        ('K2', 'J1', nor),
        ('K2', 'K1', nor),
        ('K2', 'L1', nor),
        ('K2', 'J2', nor),
        ('K2', 'L2', nor),
        ('K2', 'J3', nor),
        ('K2', 'K3', nor),
        ('K2', 'L3', nor),

        ('K3', 'J2', nor),
        ('K3', 'K2', nor),
        ('K3', 'L2', nor),
        ('K3', 'J3', nor),
        ('K3', 'L3', nor),
        ('K3', 'J4', moun),
        ('K3', 'K4', moun),
        ('K3', 'L4', nor),

        ('K4', 'J3', nor),
        ('K4', 'K3', nor),
        ('K4', 'L3', nor),
        ('K4', 'J4', nor),
        ('K4', 'L4', nor),
        ('K4', 'J5', nor),
        ('K4', 'K5', nor),
        ('K4', 'L5', nor),

        ('K5', 'J4', nor),
        ('K5', 'K4', nor),
        ('K5', 'L4', nor),
        ('K5', 'J5', nor),
        ('K5', 'L5', nor),
        ('K5', 'J6', nor),
        ('K5', 'K6', nor),
        ('K5', 'L6', nor),

        ('K6', 'J5', nor),
        ('K6', 'K5', nor),
        ('K6', 'L5', nor),
        ('K6', 'J6', nor),
        ('K6', 'L6', nor),
        ('K6', 'J7', nor),
        ('K6', 'K7', nor),
        ('K6', 'L7', nor),

        ('K7', 'J6', moun),
        ('K7', 'K6', moun),
        ('K7', 'L6', moun),
        ('K7', 'J7', nor),
        ('K7', 'L7', nor),
        ('K7', 'J8', nor),
        ('K7', 'K8', nor),
        ('K7', 'L8', nor),

        ('K8', 'J7', nor),
        ('K8', 'K7', nor),
        ('K8', 'L7', nor),
        ('K8', 'J8', nor),
        ('K8', 'L8', nor),
        ('K8', 'J9', nor),
        ('K8', 'K9', nor),
        ('K8', 'L9', nor),

        ('K9', 'J9', nor),
        ('K9', 'J8', nor),
        ('K9', 'K8', nor),
        ('K9', 'L8', nor),
        ('K9', 'L9', nor),

        ('L0', 'K0', nor),
        ('L0', 'K1', nor),
        ('L0', 'L1', nor),
        ('L0', 'M1', nor),
        ('L0', 'M0', nor),

        ('L1', 'K0', nor),
        ('L1', 'L0', nor),
        ('L1', 'M0', nor),
        ('L1', 'K1', nor),
        ('L1', 'M1', nor),
        ('L1', 'K2', nor),
        ('L1', 'L2', nor),
        ('L1', 'M2', nor),

        ('L2', 'K1', nor),
        ('L2', 'L1', nor),
        ('L2', 'M1', nor),
        ('L2', 'K2', nor),
        ('L2', 'M2', nor),
        ('L2', 'K3', nor),
        ('L2', 'L3', nor),
        ('L2', 'M3', nor),

        ('L3', 'K2', nor),
        ('L3', 'L2', nor),
        ('L3', 'M2', nor),
        ('L3', 'K3', nor),
        ('L3', 'M3', nor),
        ('L3', 'K4', moun),
        ('L3', 'L4', nor),
        ('L3', 'M4', nor),

        ('L4', 'K3', nor),
        ('L4', 'L3', nor),
        ('L4', 'M3', nor),
        ('L4', 'K4', moun),
        ('L4', 'M4', nor),
        ('L4', 'K5', moun),
        ('L4', 'L5', moun),
        ('L4', 'M5', nor),

        ('L5', 'K4', nor),
        ('L5', 'L4', nor),
        ('L5', 'M4', nor),
        ('L5', 'K5', nor),
        ('L5', 'M5', nor),
        ('L5', 'K6', nor),
        ('L5', 'L6', nor),
        ('L5', 'M6', nor),

        ('L6', 'K5', nor),
        ('L6', 'L5', nor),
        ('L6', 'M5', nor),
        ('L6', 'K6', nor),
        ('L6', 'M6', nor),
        ('L6', 'K7', nor),
        ('L6', 'L7', nor),
        ('L6', 'M7', nor),

        ('L7', 'K6', moun),
        ('L7', 'L6', moun),
        ('L7', 'M6', nor),
        ('L7', 'K7', nor),
        ('L7', 'M7', nor),
        ('L7', 'K8', nor),
        ('L7', 'L8', nor),
        ('L7', 'M8', nor),

        ('L8', 'K7', nor),
        ('L8', 'L7', nor),
        ('L8', 'M7', nor),
        ('L8', 'K8', nor),
        ('L8', 'M8', nor),
        ('L8', 'K9', nor),
        ('L8', 'L9', nor),
        ('L8', 'M9', nor),

        ('L9', 'K9', nor),
        ('L9', 'K8', nor),
        ('L9', 'L8', nor),
        ('L9', 'M8', nor),
        ('L9', 'M9', nor),

        ('M0', 'L0', nor),
        ('M0', 'L1', nor),
        ('M0', 'M1', nor),
        ('M0', 'N1', nor),
        ('M0', 'N0', nor),

        ('M1', 'L0', nor),
        ('M1', 'M0', nor),
        ('M1', 'N0', nor),
        ('M1', 'L1', nor),
        ('M1', 'N1', nor),
        ('M1', 'L2', nor),
        ('M1', 'M2', nor),
        ('M1', 'N2', nor),

        ('M2', 'L1', nor),
        ('M2', 'M1', nor),
        ('M2', 'N1', nor),
        ('M2', 'L2', nor),
        ('M2', 'N2', nor),
        ('M2', 'L3', nor),
        ('M2', 'M3', nor),
        ('M2', 'N3', nor),

        ('M3', 'L2', nor),
        ('M3', 'M2', nor),
        ('M3', 'N2', nor),
        ('M3', 'L3', nor),
        ('M3', 'N3', nor),
        ('M3', 'L4', nor),
        ('M3', 'M4', nor),
        ('M3', 'N4', nor),

        ('M4', 'L3', nor),
        ('M4', 'M3', nor),
        ('M4', 'N3', nor),
        ('M4', 'L4', nor),
        ('M4', 'N4', nor),
        ('M4', 'L5', moun),
        ('M4', 'M5', nor),
        ('M4', 'N5', nor),

        ('M5', 'L4', nor),
        ('M5', 'M4', nor),
        ('M5', 'N4', nor),
        ('M5', 'L5', moun),
        ('M5', 'N5', nor),
        ('M5', 'L6', moun),
        ('M5', 'M6', nor),
        ('M5', 'N6', nor),

        ('M6', 'L5', moun),
        ('M6', 'M5', nor),
        ('M6', 'N5', nor),
        ('M6', 'L6', moun),
        ('M6', 'N6', nor),
        ('M6', 'L7', nor),
        ('M6', 'M7', nor),
        ('M6', 'N7', nor),

        ('M7', 'L6', moun),
        ('M7', 'M6', nor),
        ('M7', 'N6', nor),
        ('M7', 'L7', nor),
        ('M7', 'N7', nor),
        ('M7', 'L8', nor),
        ('M7', 'M8', nor),
        ('M7', 'N8', nor),

        ('M8', 'L7', nor),
        ('M8', 'M7', nor),
        ('M8', 'N7', nor),
        ('M8', 'L8', nor),
        ('M8', 'N8', nor),
        ('M8', 'L9', nor),
        ('M8', 'M9', nor),
        ('M8', 'N9', nor),

        ('M9', 'L9', nor),
        ('M9', 'L8', nor),
        ('M9', 'M8', nor),
        ('M9', 'N8', nor),
        ('M9', 'N9', nor),

        ('N0', 'M0', nor),
        ('N0', 'M1', nor),
        ('N0', 'N1', nor),
        ('N0', 'O1', moun),
        ('N0', 'O0', nor),

        ('N1', 'M0', nor),
        ('N1', 'N0', nor),
        ('N1', 'O0', nor),
        ('N1', 'M1', nor),
        ('N1', 'O1', moun),
        ('N1', 'M2', nor),
        ('N1', 'N2', nor),
        ('N1', 'O2', moun),

        ('N2', 'M1', nor),
        ('N2', 'N1', nor),
        ('N2', 'O1', moun),
        ('N2', 'M2', nor),
        ('N2', 'O2', moun),
        ('N2', 'M3', nor),
        ('N2', 'N3', nor),
        ('N2', 'O3', moun),

        ('N3', 'M2', nor),
        ('N3', 'N2', nor),
        ('N3', 'O2', moun),
        ('N3', 'M3', nor),
        ('N3', 'O3', moun),
        ('N3', 'M4', nor),
        ('N3', 'N4', nor),
        ('N3', 'O4', moun),

        ('N4', 'M3', nor),
        ('N4', 'N3', nor),
        ('N4', 'O3', moun),
        ('N4', 'M4', nor),
        ('N4', 'O4', nor),
        ('N4', 'M5', nor),
        ('N4', 'N5', nor),
        ('N4', 'O5', nor),

        ('N5', 'M4', nor),
        ('N5', 'N4', nor),
        ('N5', 'O4', nor),
        ('N5', 'M5', nor),
        ('N5', 'O5', nor),
        ('N5', 'M6', nor),
        ('N5', 'N6', nor),
        ('N5', 'O6', nor),

        ('N6', 'M5', nor),
        ('N6', 'N5', nor),
        ('N6', 'O5', nor),
        ('N6', 'M6', nor),
        ('N6', 'O6', nor),
        ('N6', 'M7', nor),
        ('N6', 'N7', nor),
        ('N6', 'O7', nor),

        ('N7', 'M6', nor),
        ('N7', 'N6', nor),
        ('N7', 'O6', nor),
        ('N7', 'M7', nor),
        ('N7', 'O7', nor),
        ('N7', 'M8', nor),
        ('N7', 'N8', nor),
        ('N7', 'O8', nor),

        ('N8', 'M7', nor),
        ('N8', 'N7', nor),
        ('N8', 'O7', nor),
        ('N8', 'M8', nor),
        ('N8', 'O8', nor),
        ('N8', 'M9', nor),
        ('N8', 'N9', nor),
        ('N8', 'O9', nor),

        ('N9', 'M9', nor),
        ('N9', 'M8', nor),
        ('N9', 'N8', nor),
        ('N9', 'O8', nor),
        ('N9', 'O9', nor),

        ('O0', 'N0', nor),
        ('O0', 'N1', nor),
        ('O0', 'O1', moun),
        ('O0', 'P1', moun),
        ('O0', 'P0', nor),

        ('O1', 'N0', nor),
        ('O1', 'O0', nor),
        ('O1', 'P0', nor),
        ('O1', 'N1', nor),
        ('O1', 'P1', nor),
        ('O1', 'N2', nor),
        ('O1', 'O2', nor),
        ('O1', 'P2', nor),

        ('O2', 'N1', nor),
        ('O2', 'O1', nor),
        ('O2', 'P1', nor),
        ('O2', 'N2', nor),
        ('O2', 'P2', nor),
        ('O2', 'N3', nor),
        ('O2', 'O3', nor),
        ('O2', 'P3', nor),

        ('O3', 'N2', nor),
        ('O3', 'O2', nor),
        ('O3', 'P2', nor),
        ('O3', 'N3', nor),
        ('O3', 'P3', nor),
        ('O3', 'N4', nor),
        ('O3', 'O4', nor),
        ('O3', 'P4', nor),

        ('O4', 'N3', moun),
        ('O4', 'O3', moun),
        ('O4', 'P3', moun),
        ('O4', 'N4', nor),
        ('O4', 'P4', nor),
        ('O4', 'N5', nor),
        ('O4', 'O5', nor),
        ('O4', 'P5', nor),

        ('O5', 'N4', nor),
        ('O5', 'O4', nor),
        ('O5', 'P4', nor),
        ('O5', 'N5', nor),
        ('O5', 'P5', nor),
        ('O5', 'N6', nor),
        ('O5', 'O6', nor),
        ('O5', 'P6', nor),

        ('O6', 'N5', nor),
        ('O6', 'O5', nor),
        ('O6', 'P5', nor),
        ('O6', 'N6', nor),
        ('O6', 'P6', nor),
        ('O6', 'N7', nor),
        ('O6', 'O7', nor),
        ('O6', 'P7', nor),

        ('O7', 'N6', nor),
        ('O7', 'O6', nor),
        ('O7', 'P6', nor),
        ('O7', 'N7', nor),
        ('O7', 'P7', nor),
        ('O7', 'N8', nor),
        ('O7', 'O8', nor),
        ('O7', 'P8', nor),

        ('O8', 'N7', nor),
        ('O8', 'O7', nor),
        ('O8', 'P7', nor),
        ('O8', 'N8', nor),
        ('O8', 'P8', nor),
        ('O8', 'N9', nor),
        ('O8', 'O9', nor),
        ('O8', 'P9', nor),

        ('O9', 'N9', nor),
        ('O9', 'N8', nor),
        ('O9', 'O8', nor),
        ('O9', 'P8', nor),
        ('O9', 'P9', nor),

        ('P0', 'O0', nor),
        ('P0', 'O1', moun),
        ('P0', 'P1', moun),
        ('P0', 'Q1', moun),
        ('P0', 'Q0', nor),

        ('P1', 'O0', nor),
        ('P1', 'P0', nor),
        ('P1', 'Q0', nor),
        ('P1', 'O1', nor),
        ('P1', 'Q1', nor),
        ('P1', 'O2', nor),
        ('P1', 'P2', nor),
        ('P1', 'Q2', nor),

        ('P2', 'O1', nor),
        ('P2', 'P1', nor),
        ('P2', 'Q1', nor),
        ('P2', 'O2', nor),
        ('P2', 'Q2', nor),
        ('P2', 'O3', nor),
        ('P2', 'P3', nor),
        ('P2', 'Q3', nor),

        ('P3', 'O2', nor),
        ('P3', 'P2', nor),
        ('P3', 'Q2', nor),
        ('P3', 'O3', nor),
        ('P3', 'Q3', nor),
        ('P3', 'O4', nor),
        ('P3', 'P4', nor),
        ('P3', 'Q4', nor),

        ('P4', 'O3', moun),
        ('P4', 'P3', moun),
        ('P4', 'Q3', moun),
        ('P4', 'O4', nor),
        ('P4', 'Q4', nor),
        ('P4', 'O5', nor),
        ('P4', 'P5', nor),
        ('P4', 'Q5', nor),

        ('P5', 'O4', nor),
        ('P5', 'P4', nor),
        ('P5', 'Q4', nor),
        ('P5', 'O5', nor),
        ('P5', 'Q5', nor),
        ('P5', 'O6', nor),
        ('P5', 'P6', nor),
        ('P5', 'Q6', nor),

        ('P6', 'O5', nor),
        ('P6', 'P5', nor),
        ('P6', 'Q5', nor),
        ('P6', 'O6', nor),
        ('P6', 'Q6', nor),
        ('P6', 'O7', nor),
        ('P6', 'P7', nor),
        ('P6', 'Q7', nor),

        ('P7', 'O6', nor),
        ('P7', 'P6', nor),
        ('P7', 'Q6', nor),
        ('P7', 'O7', nor),
        ('P7', 'Q7', nor),
        ('P7', 'O8', nor),
        ('P7', 'P8', nor),
        ('P7', 'Q8', nor),

        ('P8', 'O7', nor),
        ('P8', 'P7', nor),
        ('P8', 'Q7', nor),
        ('P8', 'O8', nor),
        ('P8', 'Q8', nor),
        ('P8', 'O9', nor),
        ('P8', 'P9', nor),
        ('P8', 'Q9', nor),

        ('P9', 'O9', nor),
        ('P9', 'O8', nor),
        ('P9', 'P8', nor),
        ('P9', 'Q8', nor),
        ('P9', 'Q9', nor),

        ('Q0', 'P0', nor),
        ('Q0', 'P1', moun),
        ('Q0', 'Q1', moun),
        ('Q0', 'R1', moun),
        ('Q0', 'R0', nor),

        ('Q1', 'P0', nor),
        ('Q1', 'Q0', nor),
        ('Q1', 'R0', nor),
        ('Q1', 'P1', nor),
        ('Q1', 'R1', nor),
        ('Q1', 'P2', nor),
        ('Q1', 'Q2', nor),
        ('Q1', 'R2', nor),

        ('Q2', 'P1', nor),
        ('Q2', 'Q1', nor),
        ('Q2', 'R1', nor),
        ('Q2', 'P2', nor),
        ('Q2', 'R2', nor),
        ('Q2', 'P3', nor),
        ('Q2', 'Q3', nor),
        ('Q2', 'R3', nor),

        ('Q3', 'P2', nor),
        ('Q3', 'Q2', nor),
        ('Q3', 'R2', nor),
        ('Q3', 'P3', nor),
        ('Q3', 'R3', nor),
        ('Q3', 'P4', nor),
        ('Q3', 'Q4', nor),
        ('Q3', 'R4', nor),

        ('Q4', 'P3', moun),
        ('Q4', 'Q3', moun),
        ('Q4', 'R3', moun),
        ('Q4', 'P4', nor),
        ('Q4', 'R4', nor),
        ('Q4', 'P5', nor),
        ('Q4', 'Q5', nor),
        ('Q4', 'R5', nor),

        ('Q5', 'P4', nor),
        ('Q5', 'Q4', nor),
        ('Q5', 'R4', nor),
        ('Q5', 'P5', nor),
        ('Q5', 'R5', nor),
        ('Q5', 'P6', nor),
        ('Q5', 'Q6', nor),
        ('Q5', 'R6', nor),

        ('Q6', 'P5', nor),
        ('Q6', 'Q5', nor),
        ('Q6', 'R5', nor),
        ('Q6', 'P6', nor),
        ('Q6', 'R6', nor),
        ('Q6', 'P7', nor),
        ('Q6', 'Q7', nor),
        ('Q6', 'R7', nor),

        ('Q7', 'P6', nor),
        ('Q7', 'Q6', nor),
        ('Q7', 'R6', nor),
        ('Q7', 'P7', nor),
        ('Q7', 'R7', nor),
        ('Q7', 'P8', nor),
        ('Q7', 'Q8', nor),
        ('Q7', 'R8', nor),

        ('Q8', 'P7', nor),
        ('Q8', 'Q7', nor),
        ('Q8', 'R7', nor),
        ('Q8', 'P8', nor),
        ('Q8', 'R8', nor),
        ('Q8', 'P9', nor),
        ('Q8', 'Q9', nor),
        ('Q8', 'R9', nor),

        ('Q9', 'P9', nor),
        ('Q9', 'P8', nor),
        ('Q9', 'Q8', nor),
        ('Q9', 'R8', nor),
        ('Q9', 'R9', nor),

        ('R0', 'Q0', nor),
        ('R0', 'Q1', moun),
        ('R0', 'R1', moun),
        ('R0', 'S1', moun),
        ('R0', 'S0', nor),

        ('R1', 'Q0', nor),
        ('R1', 'R0', nor),
        ('R1', 'S0', nor),
        ('R1', 'Q1', nor),
        ('R1', 'S1', nor),
        ('R1', 'Q2', nor),
        ('R1', 'R2', nor),
        ('R1', 'S2', nor),

        ('R2', 'Q1', nor),
        ('R2', 'R1', nor),
        ('R2', 'S1', nor),
        ('R2', 'Q2', nor),
        ('R2', 'S2', nor),
        ('R2', 'Q3', nor),
        ('R2', 'R3', nor),
        ('R2', 'S3', nor),

        ('R3', 'Q2', nor),
        ('R3', 'R2', nor),
        ('R3', 'S2', nor),
        ('R3', 'Q3', nor),
        ('R3', 'S3', nor),
        ('R3', 'Q4', nor),
        ('R3', 'R4', nor),
        ('R3', 'S4', nor),

        ('R4', 'Q3', moun),
        ('R4', 'R3', moun),
        ('R4', 'S3', moun),
        ('R4', 'Q4', nor),
        ('R4', 'S4', nor),
        ('R4', 'Q5', nor),
        ('R4', 'R5', nor),
        ('R4', 'S5', nor),

        ('R5', 'Q4', nor),
        ('R5', 'R4', nor),
        ('R5', 'S4', nor),
        ('R5', 'Q5', nor),
        ('R5', 'S5', nor),
        ('R5', 'Q6', nor),
        ('R5', 'R6', nor),
        ('R5', 'S6', nor),

        ('R6', 'Q5', nor),
        ('R6', 'R5', nor),
        ('R6', 'S5', nor),
        ('R6', 'Q6', nor),
        ('R6', 'S6', nor),
        ('R6', 'Q7', nor),
        ('R6', 'R7', nor),
        ('R6', 'S7', nor),

        ('R7', 'Q6', nor),
        ('R7', 'R6', nor),
        ('R7', 'S6', nor),
        ('R7', 'Q7', nor),
        ('R7', 'S7', nor),
        ('R7', 'Q8', nor),
        ('R7', 'R8', nor),
        ('R7', 'S8', nor),

        ('R8', 'Q7', nor),
        ('R8', 'R7', nor),
        ('R8', 'S7', nor),
        ('R8', 'Q8', nor),
        ('R8', 'S8', nor),
        ('R8', 'Q9', nor),
        ('R8', 'R9', nor),
        ('R8', 'S9', nor),

        ('R9', 'Q9', nor),
        ('R9', 'Q8', nor),
        ('R9', 'R8', nor),
        ('R9', 'S8', nor),
        ('R9', 'S9', nor),

        ('S0', 'R0', nor),
        ('S0', 'R1', moun),
        ('S0', 'S1', moun),
        ('S0', 'T1', moun),
        ('S0', 'T0', nor),

        ('S1', 'R0', nor),
        ('S1', 'S0', nor),
        ('S1', 'T0', nor),
        ('S1', 'R1', nor),
        ('S1', 'T1', nor),
        ('S1', 'R2', nor),
        ('S1', 'S2', nor),
        ('S1', 'T2', nor),

        ('S2', 'R1', nor),
        ('S2', 'S1', nor),
        ('S2', 'T1', nor),
        ('S2', 'R2', nor),
        ('S2', 'T2', nor),
        ('S2', 'R3', nor),
        ('S2', 'S3', nor),
        ('S2', 'T3', nor),

        ('S3', 'R2', nor),
        ('S3', 'S2', nor),
        ('S3', 'T2', nor),
        ('S3', 'R3', nor),
        ('S3', 'T3', nor),
        ('S3', 'R4', nor),
        ('S3', 'S4', nor),
        ('S3', 'T4', nor),

        ('S4', 'R3', moun),
        ('S4', 'S3', moun),
        ('S4', 'T3', moun),
        ('S4', 'R4', nor),
        ('S4', 'T4', nor),
        ('S4', 'R5', nor),
        ('S4', 'S5', nor),
        ('S4', 'T5', nor),

        ('S5', 'R4', nor),
        ('S5', 'S4', nor),
        ('S5', 'T4', nor),
        ('S5', 'R5', nor),
        ('S5', 'T5', nor),
        ('S5', 'R6', nor),
        ('S5', 'S6', nor),
        ('S5', 'T6', nor),

        ('S6', 'R5', nor),
        ('S6', 'S5', nor),
        ('S6', 'T5', nor),
        ('S6', 'R6', nor),
        ('S6', 'T6', nor),
        ('S6', 'R7', nor),
        ('S6', 'S7', nor),
        ('S6', 'T7', nor),

        ('S7', 'R6', nor),
        ('S7', 'S6', nor),
        ('S7', 'T6', nor),
        ('S7', 'R7', nor),
        ('S7', 'T7', nor),
        ('S7', 'R8', nor),
        ('S7', 'S8', nor),
        ('S7', 'T8', nor),

        ('S8', 'R7', nor),
        ('S8', 'S7', nor),
        ('S8', 'T7', nor),
        ('S8', 'R8', nor),
        ('S8', 'T8', nor),
        ('S8', 'R9', nor),
        ('S8', 'S9', nor),
        ('S8', 'T9', nor),

        ('S9', 'R9', nor),
        ('S9', 'R8', nor),
        ('S9', 'S8', nor),
        ('S9', 'T8', nor),
        ('S9', 'T9', nor),

        ('T0', 'S0', nor),
        ('T0', 'S1', moun),
        ('T0', 'T1', moun),
        ('T0', 'U1', nor),
        ('T0', 'U0', nor),

        ('T1', 'S0', nor),
        ('T1', 'T0', nor),
        ('T1', 'U0', nor),
        ('T1', 'S1', moun),
        ('T1', 'U1', nor),
        ('T1', 'S2', moun),
        ('T1', 'T2', nor),
        ('T1', 'U2', nor),

        ('T2', 'S1', moun),
        ('T2', 'T1', moun),
        ('T2', 'U1', nor),
        ('T2', 'S2', moun),
        ('T2', 'U2', nor),
        ('T2', 'S3', moun),
        ('T2', 'T3', nor),
        ('T2', 'U3', nor),

        ('T3', 'S2', moun),
        ('T3', 'T2', nor),
        ('T3', 'U2', nor),
        ('T3', 'S3', moun),
        ('T3', 'U3', nor),
        ('T3', 'S4', moun),
        ('T3', 'T4', nor),
        ('T3', 'U4', nor),

        ('T4', 'S3', moun),
        ('T4', 'T3', nor),
        ('T4', 'U3', nor),
        ('T4', 'S4', nor),
        ('T4', 'U4', nor),
        ('T4', 'S5', nor),
        ('T4', 'T5', nor),
        ('T4', 'U5', nor),

        ('T5', 'S4', nor),
        ('T5', 'T4', nor),
        ('T5', 'U4', nor),
        ('T5', 'S5', nor),
        ('T5', 'U5', nor),
        ('T5', 'S6', nor),
        ('T5', 'T6', nor),
        ('T5', 'U6', nor),

        ('T6', 'S5', nor),
        ('T6', 'T5', nor),
        ('T6', 'U5', nor),
        ('T6', 'S6', nor),
        ('T6', 'U6', nor),
        ('T6', 'S7', nor),
        ('T6', 'T7', nor),
        ('T6', 'U7', nor),

        ('T7', 'S6', nor),
        ('T7', 'T6', nor),
        ('T7', 'U6', nor),
        ('T7', 'S7', nor),
        ('T7', 'U7', nor),
        ('T7', 'S8', nor),
        ('T7', 'T8', nor),
        ('T7', 'U8', nor),

        ('T8', 'S7', nor),
        ('T8', 'T7', nor),
        ('T8', 'U7', nor),
        ('T8', 'S8', nor),
        ('T8', 'U8', nor),
        ('T8', 'S9', nor),
        ('T8', 'T9', nor),
        ('T8', 'U9', nor),

        ('T9', 'S9', nor),
        ('T9', 'S8', nor),
        ('T9', 'T8', nor),
        ('T9', 'U8', nor),
        ('T9', 'U9', nor),

        ('U0', 'T0', nor),
        ('U0', 'T1', nor),
        ('U0', 'U1', nor),
        ('U0', 'W1', nor),
        ('U0', 'W0', nor),

        ('U1', 'T0', nor),
        ('U1', 'U0', nor),
        ('U1', 'W0', nor),
        ('U1', 'T1', nor),
        ('U1', 'W1', nor),
        ('U1', 'T2', nor),
        ('U1', 'U2', nor),
        ('U1', 'W2', nor),

        ('U2', 'T1', nor),
        ('U2', 'U1', nor),
        ('U2', 'W1', nor),
        ('U2', 'T2', nor),
        ('U2', 'W2', nor),
        ('U2', 'T3', nor),
        ('U2', 'U3', nor),
        ('U2', 'W3', nor),

        ('U3', 'T2', nor),
        ('U3', 'U2', nor),
        ('U3', 'W2', nor),
        ('U3', 'T3', nor),
        ('U3', 'W3', nor),
        ('U3', 'T4', nor),
        ('U3', 'U4', nor),
        ('U3', 'W4', nor),

        ('U4', 'T3', nor),
        ('U4', 'U3', nor),
        ('U4', 'W3', nor),
        ('U4', 'T4', nor),
        ('U4', 'W4', nor),
        ('U4', 'T5', nor),
        ('U4', 'U5', nor),
        ('U4', 'W5', nor),

        ('U5', 'T4', nor),
        ('U5', 'U4', nor),
        ('U5', 'W4', nor),
        ('U5', 'T5', nor),
        ('U5', 'W5', nor),
        ('U5', 'T6', nor),
        ('U5', 'U6', nor),
        ('U5', 'W6', nor),

        ('U6', 'T5', nor),
        ('U6', 'U5', nor),
        ('U6', 'W5', nor),
        ('U6', 'T6', nor),
        ('U6', 'W6', nor),
        ('U6', 'T7', nor),
        ('U6', 'U7', nor),
        ('U6', 'W7', nor),

        ('U7', 'T6', nor),
        ('U7', 'U6', nor),
        ('U7', 'W6', nor),
        ('U7', 'T7', nor),
        ('U7', 'W7', nor),
        ('U7', 'T8', nor),
        ('U7', 'U8', nor),
        ('U7', 'W8', nor),

        ('U8', 'T7', nor),
        ('U8', 'U7', nor),
        ('U8', 'W7', nor),
        ('U8', 'T8', nor),
        ('U8', 'W8', nor),
        ('U8', 'T9', nor),
        ('U8', 'U9', nor),
        ('U8', 'W9', nor),

        ('U9', 'T9', nor),
        ('U9', 'T8', nor),
        ('U9', 'U8', nor),
        ('U9', 'W8', nor),
        ('U9', 'W9', nor),

        ('W0', 'U0', nor),
        ('W0', 'U1', nor),
        ('W0', 'W1', nor),
        ('W0', 'X1', nor),
        ('W0', 'X0', nor),

        ('W1', 'U0', nor),
        ('W1', 'W0', nor),
        ('W1', 'X0', nor),
        ('W1', 'U1', nor),
        ('W1', 'X1', nor),
        ('W1', 'U2', nor),
        ('W1', 'W2', nor),
        ('W1', 'X2', nor),

        ('W2', 'U1', nor),
        ('W2', 'W1', nor),
        ('W2', 'X1', nor),
        ('W2', 'U2', nor),
        ('W2', 'X2', nor),
        ('W2', 'U3', nor),
        ('W2', 'W3', nor),
        ('W2', 'X3', nor),

        ('W3', 'U2', nor),
        ('W3', 'W2', nor),
        ('W3', 'X2', nor),
        ('W3', 'U3', nor),
        ('W3', 'X3', nor),
        ('W3', 'U4', nor),
        ('W3', 'W4', nor),
        ('W3', 'X4', nor),

        ('W4', 'U3', nor),
        ('W4', 'W3', nor),
        ('W4', 'X3', nor),
        ('W4', 'U4', nor),
        ('W4', 'X4', nor),
        ('W4', 'U5', nor),
        ('W4', 'W5', nor),
        ('W4', 'X5', nor),

        ('W5', 'U4', nor),
        ('W5', 'W4', nor),
        ('W5', 'X4', nor),
        ('W5', 'U5', nor),
        ('W5', 'X5', nor),
        ('W5', 'U6', nor),
        ('W5', 'W6', nor),
        ('W5', 'X6', nor),

        ('W6', 'U5', nor),
        ('W6', 'W5', nor),
        ('W6', 'X5', nor),
        ('W6', 'U6', nor),
        ('W6', 'X6', nor),
        ('W6', 'U7', nor),
        ('W6', 'W7', nor),
        ('W6', 'X7', nor),

        ('W7', 'U6', nor),
        ('W7', 'W6', nor),
        ('W7', 'X6', nor),
        ('W7', 'U7', nor),
        ('W7', 'X7', nor),
        ('W7', 'U8', nor),
        ('W7', 'W8', nor),
        ('W7', 'X8', nor),

        ('W8', 'U7', nor),
        ('W8', 'W7', nor),
        ('W8', 'X7', nor),
        ('W8', 'U8', nor),
        ('W8', 'X8', nor),
        ('W8', 'U9', nor),
        ('W8', 'W9', nor),
        ('W8', 'X9', nor),

        ('W9', 'U9', nor),
        ('W9', 'U8', nor),
        ('W9', 'W8', nor),
        ('W9', 'X8', nor),
        ('W9', 'X9', nor),

        ('X0', 'W0', nor),
        ('X0', 'W1', nor),
        ('X0', 'X1', nor),
        ('X0', 'Y1', nor),
        ('X0', 'Y0', nor),

        ('X1', 'W0', nor),
        ('X1', 'X0', nor),
        ('X1', 'Y0', nor),
        ('X1', 'W1', nor),
        ('X1', 'Y1', nor),
        ('X1', 'W2', nor),
        ('X1', 'X2', nor),
        ('X1', 'Y2', nor),

        ('X2', 'W1', nor),
        ('X2', 'X1', nor),
        ('X2', 'Y1', nor),
        ('X2', 'W2', nor),
        ('X2', 'Y2', nor),
        ('X2', 'W3', nor),
        ('X2', 'X3', nor),
        ('X2', 'Y3', nor),

        ('X3', 'W2', nor),
        ('X3', 'X2', nor),
        ('X3', 'Y2', nor),
        ('X3', 'W3', nor),
        ('X3', 'Y3', nor),
        ('X3', 'W4', nor),
        ('X3', 'X4', nor),
        ('X3', 'Y4', nor),

        ('X4', 'W3', nor),
        ('X4', 'X3', nor),
        ('X4', 'Y3', nor),
        ('X4', 'W4', nor),
        ('X4', 'Y4', nor),
        ('X4', 'W5', nor),
        ('X4', 'X5', nor),
        ('X4', 'Y5', nor),

        ('X5', 'W4', nor),
        ('X5', 'X4', nor),
        ('X5', 'Y4', nor),
        ('X5', 'W5', nor),
        ('X5', 'Y5', nor),
        ('X5', 'W6', nor),
        ('X5', 'X6', nor),
        ('X5', 'Y6', nor),

        ('X6', 'W5', nor),
        ('X6', 'X5', nor),
        ('X6', 'Y5', nor),
        ('X6', 'W6', nor),
        ('X6', 'Y6', nor),
        ('X6', 'W7', nor),
        ('X6', 'X7', nor),
        ('X6', 'Y7', nor),

        ('X7', 'W6', nor),
        ('X7', 'X6', nor),
        ('X7', 'Y6', nor),
        ('X7', 'W7', nor),
        ('X7', 'Y7', nor),
        ('X7', 'W8', nor),
        ('X7', 'X8', nor),
        ('X7', 'Y8', nor),

        ('X8', 'W7', nor),
        ('X8', 'X7', nor),
        ('X8', 'Y7', nor),
        ('X8', 'W8', nor),
        ('X8', 'Y8', nor),
        ('X8', 'W9', nor),
        ('X8', 'X9', nor),
        ('X8', 'Y9', nor),

        ('X9', 'W9', nor),
        ('X9', 'W8', nor),
        ('X9', 'X8', nor),
        ('X9', 'Y8', nor),
        ('X9', 'Y9', nor),

        ('Y0', 'X0', nor),
        ('Y0', 'X1', nor),
        ('Y0', 'Y1', nor),
        ('Y0', 'Z1', nor),
        ('Y0', 'Z0', nor),

        ('Y1', 'X0', nor),
        ('Y1', 'Y0', nor),
        ('Y1', 'Z0', nor),
        ('Y1', 'X1', nor),
        ('Y1', 'Z1', nor),
        ('Y1', 'X2', nor),
        ('Y1', 'Y2', nor),
        ('Y1', 'Z2', nor),

        ('Y2', 'X1', nor),
        ('Y2', 'Y1', nor),
        ('Y2', 'Z1', nor),
        ('Y2', 'X2', nor),
        ('Y2', 'Z2', nor),
        ('Y2', 'X3', nor),
        ('Y2', 'Y3', nor),
        ('Y2', 'Z3', nor),

        ('Y3', 'X2', nor),
        ('Y3', 'Y2', nor),
        ('Y3', 'Z2', nor),
        ('Y3', 'X3', nor),
        ('Y3', 'Z3', nor),
        ('Y3', 'X4', nor),
        ('Y3', 'Y4', nor),
        ('Y3', 'Z4', nor),

        ('Y4', 'X3', nor),
        ('Y4', 'Y3', nor),
        ('Y4', 'Z3', nor),
        ('Y4', 'X4', nor),
        ('Y4', 'Z4', nor),
        ('Y4', 'X5', nor),
        ('Y4', 'Y5', nor),
        ('Y4', 'Z5', nor),

        ('Y5', 'X4', nor),
        ('Y5', 'Y4', nor),
        ('Y5', 'Z4', nor),
        ('Y5', 'X5', nor),
        ('Y5', 'Z5', nor),
        ('Y5', 'X6', nor),
        ('Y5', 'Y6', nor),
        ('Y5', 'Z6', nor),

        ('Y6', 'X5', nor),
        ('Y6', 'Y5', nor),
        ('Y6', 'Z5', nor),
        ('Y6', 'X6', nor),
        ('Y6', 'Z6', nor),
        ('Y6', 'X7', nor),
        ('Y6', 'Y7', nor),
        ('Y6', 'Z7', nor),

        ('Y7', 'X6', nor),
        ('Y7', 'Y6', nor),
        ('Y7', 'Z6', nor),
        ('Y7', 'X7', nor),
        ('Y7', 'Z7', nor),
        ('Y7', 'X8', nor),
        ('Y7', 'Y8', nor),
        ('Y7', 'Z8', nor),

        ('Y8', 'X7', nor),
        ('Y8', 'Y7', nor),
        ('Y8', 'Z7', nor),
        ('Y8', 'X8', nor),
        ('Y8', 'Z8', nor),
        ('Y8', 'X9', nor),
        ('Y8', 'Y9', nor),
        ('Y8', 'Z9', nor),

        ('Y9', 'X9', nor),
        ('Y9', 'X8', nor),
        ('Y9', 'Y8', nor),
        ('Y9', 'Z8', nor),
        ('Y9', 'Z9', nor),

        ('Z0', 'Y0', nor),
        ('Z0', 'Y1', nor),
        ('Z0', 'Z1', nor),

        ('Z1', 'Z0', nor),
        ('Z1', 'Y0', nor),
        ('Z1', 'Y1', nor),
        ('Z1', 'Y2', nor),
        ('Z1', 'Z2', nor),

        ('Z2', 'Z1', nor),
        ('Z2', 'Y1', nor),
        ('Z2', 'Y2', nor),
        ('Z2', 'Y3', nor),
        ('Z2', 'Z3', nor),

        ('Z3', 'Z2', nor),
        ('Z3', 'Y2', nor),
        ('Z3', 'Y3', nor),
        ('Z3', 'Y4', nor),
        ('Z3', 'Z4', nor),

        ('Z4', 'Z3', nor),
        ('Z4', 'Y3', nor),
        ('Z4', 'Y4', nor),
        ('Z4', 'Y5', nor),
        ('Z4', 'Z5', nor),

        ('Z5', 'Z4', nor),
        ('Z5', 'Y4', nor),
        ('Z5', 'Y5', nor),
        ('Z5', 'Y6', nor),
        ('Z5', 'Z6', nor),

        ('Z6', 'Z5', nor),
        ('Z6', 'Y5', nor),
        ('Z6', 'Y6', nor),
        ('Z6', 'Y7', nor),
        ('Z6', 'Z7', nor),

        ('Z7', 'Z6', nor),
        ('Z7', 'Y6', nor),
        ('Z7', 'Y7', nor),
        ('Z7', 'Y8', nor),
        ('Z7', 'Z8', nor),

        ('Z8', 'Z7', nor),
        ('Z8', 'Y7', nor),
        ('Z8', 'Y8', nor),
        ('Z8', 'Y9', nor),
        ('Z8', 'Z9', nor),

        ('Z9', 'Y9', nor),
        ('Z9', 'Y8', nor),
        ('Z9', 'Z8', nor)]